### ISSUE TITLE
.asmdef should be "RoyTheunissen.Graphing" to be consistent

### ISSUE THREAD

**Issue by AldeRoberge** [RoyTheunissen/Value-Graphing#2]
Hello, I think the .asmdef for this project should be "RoyTheunissen.Graphing" to be consistant with the package name :

![image](https://github.com/RoyTheunissen/Value-Graphing/assets/4276275/d1ef84cd-e9e3-4f71-9e5c-6b28639a6f75)

Since FMODSyntax follows that principle

**Comment by RoyTheunissen** [comment]
Hey Alexandre! Slow response because it's been a very busy week, but I've gone through the repositories I'm actively working on and updated the .asmdefs to use the `RoyTheunissen.` prefix as suggested.

Thanks for reporting it 👍
